mylibft: update test script, remove unneeded tests

diff --git a/mylibft/testlibft b/mylibft/testlibft
--- a/mylibft/testlibft
+++ b/mylibft/testlibft
@@ -1,57 +1,42 @@
 #!/bin/bash
 
+COLOR_GREEN="\033[0;32m"
+COLOR_NONE="\033[0m"
+COLOR_RED="\033[0;31m"
+
+result=0
+
+echo "----   NORMINETTE   ----"
+
+norm=$(norminette libft/ | grep -v ': OK!$')
+if [ $(echo "$norm" | wc -w) -eq 0 ]
+then
+	echo -e "${COLOR_GREEN}No norm errors!${COLOR_NONE}"
+else
+	echo -e "${COLOR_RED}$norm${COLOR_NONE}"
+	result=1
+fi
+
+echo "----   COMPILE   ----"
+
 make -s -C tests/ all clean
-
-echo "---- PARSENUM ----"
-
-valgrind --log-fd=10 tests/parsenum_tester "01" "0" "1" "101011" "-111" "   +1011" "++1" "55" "10151" "10 01 10 01" > parsenum_output_binary.out 10>>valgrind.out
-diff tests/parsenum_output_binary.txt parsenum_output_binary.out > /dev/null
-if [ $? -ne 0 ]
+if [ $? -eq 0 ]
 then
-	echo "Binary test KO"
+	echo -e "${COLOR_GREEN}Compilation successful!${COLOR_NONE}"
 else
-	echo "Binary test OK"
+	echo -e "${COLOR_RED}Compilation failed...${COLOR_NONE}"
+	result=1
+	exit $result
 fi
 
-valgrind --log-fd=10 tests/parsenum_tester "0123456789" "0" "5" "+0" "-0" "+5" "-5" "     500" "-432" "  -6" "+-7" "kkk" "1k23j" "2147483647" "2147483648" "-2147483648" "-2147483647" "-2147483649" > parsenum_output_decimal.out 10>>valgrind.out
-diff tests/parsenum_output_decimal.txt parsenum_output_decimal.out > /dev/null
+echo "----   TESTS   ----"
+
+valgrind --xml-fd=10 --show-leak-kinds=all --xml=yes tests/tester 10>valgrind.out
 if [ $? -ne 0 ]
 then
-	echo "Decimal test KO"
-else
-	echo "Decimal test OK"
-fi
-
-echo "---- PRINT ----"
-
-valgrind --log-fd=10 tests/printf_tester > printf_output.out 10>>valgrind.out
-diff tests/printf_output.txt printf_output.out > /dev/null
-if [ $? -ne 0 ]
-then
-	echo "Printf: Test KO"
-else
-	echo "Printf: Test OK"
-fi
-
-echo "---- PATH ----"
-
-valgrind --log-fd=10 tests/basename_tester / /boot /home/ander // //a//b //a//b/ libft libft/ libft// a/b/c/d/ > basename_output.out 10>>valgrind.out
-diff tests/basename_output.txt basename_output.out > /dev/null
-if [ $? -ne 0 ]
-then
-	echo "Basename: Test KO"
-else
-	echo "Basename: Test OK"
-fi
-
-valgrind --log-fd=10 tests/dirname_tester / /boot /home/ander // //a//b //a//b/ libft libft/ libft// a/b/c/d/ > dirname_output.out 10>>valgrind.out
-diff tests/dirname_output.txt dirname_output.out > /dev/null
-if [ $? -ne 0 ]
-then
-	echo "Dirname: Test KO"
-else
-	echo "Dirname: Test OK"
+	result=1
 fi
 
 make -s -C tests/ fclean
-rm -f basename_output.out dirname_output.out parsenum_output_binary.out parsenum_output_decimal.out printf_output.out
+
+exit $result
