pipex: add tests for empty input and output names

diff --git a/pipex/test b/pipex/test
--- a/pipex/test
+++ b/pipex/test
@@ -81,6 +81,27 @@ fi
 <tests/file1.txt "" | "" >file2.out
 ../util/testdiff file1.out file2.out
 
+../util/printtitle "TEST WITH EMPTY INPUT FILE NAME"
+repo/pipex "" cat cat file1.out
+if [ $? -eq 0 ]
+then
+	echo -e "${green}Command returns success, OK${nocolor}"
+else
+	echo -e "${red}Command returns failure, KO${nocolor}"
+fi
+<"" cat | cat >file2.out
+../util/testdiff file1.out file2.out
+
+../util/printtitle "TEST WITH EMPTY OUTPUT FILE NAME"
+repo/pipex tests/file1.txt cat cat ""
+if [ $? -ne 0 ]
+then
+	echo -e "${green}Command returns failure, OK${nocolor}"
+else
+	echo -e "${red}Command returns success, KO${nocolor}"
+fi
+<tests/file1.txt cat | cat >""
+
 ../util/printtitle "TEST WITH INVALID COMMAND"
 repo/pipex tests/file1.txt "k" "cat" file1.out
 if [ $? -eq 0 ]
